//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.DbMigration.Bridges.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITS.DbMigration.Bridges.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO bridges_defect_scroll_section(id, full_name, name) VALUES
        ///(1, &apos;1 Дефекты материалов//1.1 Дефекты бетона в железобетонных конструкциях//1.1.1 Дефекты поверхности&apos;, &apos;Дефекты поверхности бетона в ж//б конструкциях&apos;),
        ///(2, &apos;1 Дефекты материалов//1.1 Дефекты бетона в железобетонных конструкциях//1.1.2 Разрушение защитного слоя&apos;, &apos;Разрушение защитного слоя бетона в ж//б конструкциях&apos;),
        ///(3, &apos;1 Дефекты материалов//1.1 Дефекты бетона в железобетонных конструкциях//1.1.3 Трещины&apos;, &apos;Трещины бетона в ж//б [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string InsertDefectScrollSections {
            get {
                return ResourceManager.GetString("InsertDefectScrollSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO bridges_defect_type(id, name, pattern, section_id) VALUES     
        ///--1 ДЕФЕКТЫ МАТЕРИАЛОВ
        ///--1.1 Дефекты бетона в железобетонных конструкциях
        ///--1.1.1 Дефекты поверхности
        ///(1, &apos;Протечки&apos;, &apos;F или L:float&apos;, 1),
        ///(2, &apos;Выщелачивание&apos;, &apos;F или L:float&apos;, 1),
        ///(3, &apos;Шелушение поверхностное (до 5 мм глубиной)&apos;, &apos;F или L:float&apos;, 1),
        ///(4, &apos;Раковины и сколы незначительной глубины (до 10мм)&apos;, &apos;F или L:float&apos;, 1),
        ///(5, &apos;Раковины и сколы глубиной более 10мм&apos;, &apos;F или L:float&apos;, 1),
        ///--1.1.2 Разрушение защитного слоя [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string InsertDefectTypes {
            get {
                return ResourceManager.GetString("InsertDefectTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO bridges_material(id, name) VALUES
        ///(1, &apos;Железобетон&apos;), 
        ///(2, &apos;Бетон&apos;), 
        ///(3, &apos;Сталь&apos;), 
        ///(4, &apos;Сталежелезобетон&apos;), 
        ///(5, &apos;Бутобетон&apos;), 
        ///(6, &apos;Каменная или бетонная кладка&apos;), 
        ///(7, &apos;Железобетон преднапряженный&apos;),
        ///(8, &apos;Алюминий&apos;), 
        ///(9, &apos;Композитный материал&apos;), 
        ///(10, &apos;Древесина&apos;), 
        ///(11, &apos;Древесина клееная&apos;),
        ///(12, &apos;Прочее&apos;), 
        ///(13, &apos;Нет данных&apos;).
        /// </summary>
        internal static string InsertMaterials {
            get {
                return ResourceManager.GetString("InsertMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO bridges_territory(id, name) VALUES
        ///(01,&apos;Адыгея республика&apos;),
        ///(02,&apos;Башкортостан республика&apos;),
        ///(03,&apos;Бурятия республика&apos;),
        ///(04,&apos;Алтай республика&apos;),
        ///(05,&apos;Дагестан республика&apos;),
        ///(06,&apos;Ингушетия республика&apos;),
        ///(07,&apos;Кабардино-Балкарская республика&apos;),
        ///(08,&apos;Калмыкия республика&apos;),
        ///(09,&apos;Карачаево-Черкесская республика&apos;),
        ///(10,&apos;Карелия республика&apos;),
        ///(11,&apos;Коми республика&apos;),
        ///(12,&apos;Марий Эл республика&apos;),
        ///(13,&apos;Мордовия республика&apos;),
        ///(14,&apos;Саха /Якутия/ республика&apos;),
        ///(15,&apos;Северная Осетия - Алания респу [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string InsertTerritories {
            get {
                return ResourceManager.GetString("InsertTerritories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO bridges_typical_project(id, name, target) VALUES
        ///(1, &apos;3.500.1-1.93&apos;, &apos;Опоры&apos;), 
        ///(2, &apos;Шифр 2070ТПP&apos;, &apos;Опоры&apos;),
        ///(3, &apos;3.501.1-124 (инв.№1241/1-3)&apos;, &apos;Опоры&apos;),
        ///(4, &apos;1.011.1-11м.97&apos;, &apos;Опоры&apos;),
        ///(5, &apos;Шифр 2416&apos;, &apos;Опоры&apos;),
        ///(6, &apos;Шифр 1279&apos;, &apos;Опоры&apos;),
        ///(7, &apos;Инв.№1067/11 инв.№1067/11- доп.&apos;, &apos;Опоры&apos;),
        ///
        ///(8, &apos;3.501.1-146&apos;, &apos;Пролётные строения&apos;),
        ///(9, &apos;3.501.1-175.93&apos;, &apos;Пролётные строения&apos;),
        ///(10, &apos;Шифр 2243РЧ&apos;, &apos;Пролётные строения&apos;),
        ///(11, &apos;Шифр 2244РЧ&apos;, &apos;Пролётные строения&apos;),
        ///(12, &apos;Шифр 2291РЧ&apos;, &apos;Пр [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string InsertTypicalProjects {
            get {
                return ResourceManager.GetString("InsertTypicalProjects", resourceCulture);
            }
        }
    }
}
