//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.MapObjects.BridgesMapObject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITS.MapObjects.BridgesMapObject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функционал изменений.
        /// </summary>
        internal static string AcceptBridgesGroupName {
            get {
                return ResourceManager.GetString("AcceptBridgesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AcceptBridgesImageSource {
            get {
                object obj = ResourceManager.GetObject("AcceptBridgesImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить все изменения.
        /// </summary>
        internal static string AcceptBridgesUserFunctionalName {
            get {
                return ResourceManager.GetString("AcceptBridgesUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddBridgeImageSource {
            get {
                object obj = ResourceManager.GetObject("AddBridgeImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить мост.
        /// </summary>
        internal static string AddBridgeUserFunctionalName {
            get {
                return ResourceManager.GetString("AddBridgeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Aqueduct {
            get {
                object obj = ResourceManager.GetObject("Aqueduct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArchedBeamExternallySpacerRideTop {
            get {
                object obj = ResourceManager.GetObject("ArchedBeamExternallySpacerRideTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArchedBeamExternallyWithoutExpansion {
            get {
                object obj = ResourceManager.GetObject("ArchedBeamExternallyWithoutExpansion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArchedDoubleHinged {
            get {
                object obj = ResourceManager.GetObject("ArchedDoubleHinged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArchedFarmRideMiddle {
            get {
                object obj = ResourceManager.GetObject("ArchedFarmRideMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArchedHingeless {
            get {
                object obj = ResourceManager.GetObject("ArchedHingeless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArchedThreeHinged {
            get {
                object obj = ResourceManager.GetObject("ArchedThreeHinged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArchedTightening {
            get {
                object obj = ResourceManager.GetObject("ArchedTightening", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ATVAdd {
            get {
                object obj = ResourceManager.GetObject("ATVAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ATVCopy {
            get {
                object obj = ResourceManager.GetObject("ATVCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ATVDelete {
            get {
                object obj = ResourceManager.GetObject("ATVDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ATVDown {
            get {
                object obj = ResourceManager.GetObject("ATVDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ATVEdit {
            get {
                object obj = ResourceManager.GetObject("ATVEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ATVUp {
            get {
                object obj = ResourceManager.GetObject("ATVUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функционал изменений.
        /// </summary>
        internal static string BackBridgesGroupName {
            get {
                return ResourceManager.GetString("BackBridgesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackBridgesImageSource {
            get {
                object obj = ResourceManager.GetObject("BackBridgesImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить последнее изменение.
        /// </summary>
        internal static string BackBridgesUserFunctionalName {
            get {
                return ResourceManager.GetString("BackBridgesUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BeamCantilever {
            get {
                object obj = ResourceManager.GetObject("BeamCantilever", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BeamCantileverSuspendedSpan {
            get {
                object obj = ResourceManager.GetObject("BeamCantileverSuspendedSpan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BeamCut {
            get {
                object obj = ResourceManager.GetObject("BeamCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BeamTemperatureContinuous {
            get {
                object obj = ResourceManager.GetObject("BeamTemperatureContinuous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты.
        /// </summary>
        internal static string BindBridgeToVillageGroupName {
            get {
                return ResourceManager.GetString("BindBridgeToVillageGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BindBridgeToVillageImageSource {
            get {
                object obj = ResourceManager.GetObject("BindBridgeToVillageImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязать мост к ближайшему населённому пункту.
        /// </summary>
        internal static string BindBridgeToVillageUserFunctionalName {
            get {
                return ResourceManager.GetString("BindBridgeToVillageUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bridge {
            get {
                object obj = ResourceManager.GetObject("Bridge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведомости.
        /// </summary>
        internal static string BridgeInfoGroupName {
            get {
                return ResourceManager.GetString("BridgeInfoGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BridgeInfoImageSource {
            get {
                object obj = ResourceManager.GetObject("BridgeInfoImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о мосте.
        /// </summary>
        internal static string BridgeInfoUserFunctionalName {
            get {
                return ResourceManager.GetString("BridgeInfoUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мостовые сооружения.
        /// </summary>
        internal static string BridgeLayerAlias {
            get {
                return ResourceManager.GetString("BridgeLayerAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 760.
        /// </summary>
        internal static string BridgeLayerOrderIndex {
            get {
                return ResourceManager.GetString("BridgeLayerOrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведомости.
        /// </summary>
        internal static string BridgeSummaryGroupName {
            get {
                return ResourceManager.GetString("BridgeSummaryGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BridgeSummaryImageSource {
            get {
                object obj = ResourceManager.GetObject("BridgeSummaryImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сводная ведомость мостов.
        /// </summary>
        internal static string BridgeSummaryUserFunctionalName {
            get {
                return ResourceManager.GetString("BridgeSummaryUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CableStayedWithStiffeningBeam {
            get {
                object obj = ResourceManager.GetObject("CableStayedWithStiffeningBeam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функционал изменений.
        /// </summary>
        internal static string CancelBridgesGroupName {
            get {
                return ResourceManager.GetString("CancelBridgesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CancelBridgesImageSource {
            get {
                object obj = ResourceManager.GetObject("CancelBridgesImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить все изменения.
        /// </summary>
        internal static string CancelBridgesUserFunctionalName {
            get {
                return ResourceManager.GetString("CancelBridgesUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с геометрией.
        /// </summary>
        internal static string CancelGroupingBridgesGroupName {
            get {
                return ResourceManager.GetString("CancelGroupingBridgesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CancelGroupingBridgesImageSource {
            get {
                object obj = ResourceManager.GetObject("CancelGroupingBridgesImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить группировку.
        /// </summary>
        internal static string CancelGroupingBridgesUserFunctionalName {
            get {
                return ResourceManager.GetString("CancelGroupingBridgesUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CattleDrive {
            get {
                object obj = ResourceManager.GetObject("CattleDrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Combined {
            get {
                object obj = ResourceManager.GetObject("Combined", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ContinuousBeamConstantHeight {
            get {
                object obj = ResourceManager.GetObject("ContinuousBeamConstantHeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ContinuousBeamVariableHeight {
            get {
                object obj = ResourceManager.GetObject("ContinuousBeamVariableHeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CopyPasteBridgeImageSource {
            get {
                object obj = ResourceManager.GetObject("CopyPasteBridgeImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать мост.
        /// </summary>
        internal static string CopyPasteBridgeUserFunctionalName {
            get {
                return ResourceManager.GetString("CopyPasteBridgeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CrossbarAndStrut {
            get {
                object obj = ResourceManager.GetObject("CrossbarAndStrut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteBridgeImageSource {
            get {
                object obj = ResourceManager.GetObject("DeleteBridgeImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить мост.
        /// </summary>
        internal static string DeleteBridgeUserFunctionalName {
            get {
                return ResourceManager.GetString("DeleteBridgeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты.
        /// </summary>
        internal static string DirectoryBridgesGroupName {
            get {
                return ResourceManager.GetString("DirectoryBridgesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DirectoryBridgesImageSource {
            get {
                object obj = ResourceManager.GetObject("DirectoryBridgesImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник.
        /// </summary>
        internal static string DirectoryBridgesUserFunctionalName {
            get {
                return ResourceManager.GetString("DirectoryBridgesUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Drawbridge {
            get {
                object obj = ResourceManager.GetObject("Drawbridge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DropDownSwing {
            get {
                object obj = ResourceManager.GetObject("DropDownSwing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditBridgeImageSource {
            get {
                object obj = ResourceManager.GetObject("EditBridgeImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать мост.
        /// </summary>
        internal static string EditBridgeUserFunctionalName {
            get {
                return ResourceManager.GetString("EditBridgeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с геометрией.
        /// </summary>
        internal static string EditGeometryBridgeGroupName {
            get {
                return ResourceManager.GetString("EditGeometryBridgeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditGeometryBridgeImageSource {
            get {
                object obj = ResourceManager.GetObject("EditGeometryBridgeImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор геометрии.
        /// </summary>
        internal static string EditGeometryBridgeUserFunctionalName {
            get {
                return ResourceManager.GetString("EditGeometryBridgeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_ClosedMetalCompensator {
            get {
                object obj = ResourceManager.GetObject("EJT_ClosedMetalCompensator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_ClosedTormaJoint {
            get {
                object obj = ResourceManager.GetObject("EJT_ClosedTormaJoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_FilledMasticAndMetalCompensator {
            get {
                object obj = ResourceManager.GetObject("EJT_FilledMasticAndMetalCompensator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_FilledMasticStellEdging {
            get {
                object obj = ResourceManager.GetObject("EJT_FilledMasticStellEdging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_FilledRubberOrPolymerCompensator {
            get {
                object obj = ResourceManager.GetObject("EJT_FilledRubberOrPolymerCompensator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_FilledTwoRubberCompensatorModular {
            get {
                object obj = ResourceManager.GetObject("EJT_FilledTwoRubberCompensatorModular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_OverlappedCombType {
            get {
                object obj = ResourceManager.GetObject("EJT_OverlappedCombType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_OverlappedSlidingType {
            get {
                object obj = ResourceManager.GetObject("EJT_OverlappedSlidingType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_OverlappedSteelSliding {
            get {
                object obj = ResourceManager.GetObject("EJT_OverlappedSteelSliding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EJT_OverlappedSteelSlidingDoubleSidedBalanced {
            get {
                object obj = ResourceManager.GetObject("EJT_OverlappedSteelSlidingDoubleSidedBalanced", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Estacada {
            get {
                object obj = ResourceManager.GetObject("Estacada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillType {
            get {
                object obj = ResourceManager.GetObject("FillType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FlyingFerry {
            get {
                object obj = ResourceManager.GetObject("FlyingFerry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функционал изменений.
        /// </summary>
        internal static string ForwardBridgesGroupName {
            get {
                return ResourceManager.GetString("ForwardBridgesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ForwardBridgesImageSource {
            get {
                object obj = ResourceManager.GetObject("ForwardBridgesImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуть изменение.
        /// </summary>
        internal static string ForwardBridgesUserFunctionalName {
            get {
                return ResourceManager.GetString("ForwardBridgesUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame {
            get {
                object obj = ResourceManager.GetObject("Frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FrameConsole {
            get {
                object obj = ResourceManager.GetObject("FrameConsole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FrameInclinedSupports {
            get {
                object obj = ResourceManager.GetObject("FrameInclinedSupports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FrameSuspended {
            get {
                object obj = ResourceManager.GetObject("FrameSuspended", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FrameVShapedSupports {
            get {
                object obj = ResourceManager.GetObject("FrameVShapedSupports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с геометрией.
        /// </summary>
        internal static string GroupBridgesGroupName {
            get {
                return ResourceManager.GetString("GroupBridgesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroupBridgesImageSource {
            get {
                object obj = ResourceManager.GetObject("GroupBridgesImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сгруппировать геообъекты.
        /// </summary>
        internal static string GroupBridgesUserFunctionalName {
            get {
                return ResourceManager.GetString("GroupBridgesUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HangingEmbeddedRopesInAnchorAbutments {
            get {
                object obj = ResourceManager.GetObject("HangingEmbeddedRopesInAnchorAbutments", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HangingWithRopesStiffeningBeam {
            get {
                object obj = ResourceManager.GetObject("HangingWithRopesStiffeningBeam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ITSBackground1 {
            get {
                object obj = ResourceManager.GetObject("ITSBackground1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon ITSGIS_Icon {
            get {
                object obj = ResourceManager.GetObject("ITSGIS_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ITSGISIcon {
            get {
                object obj = ResourceManager.GetObject("ITSGISIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ITSLogo1 {
            get {
                object obj = ResourceManager.GetObject("ITSLogo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с геометрией.
        /// </summary>
        internal static string MoveBridgeGroupName {
            get {
                return ResourceManager.GetString("MoveBridgeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveBridgeImageSource {
            get {
                object obj = ResourceManager.GetObject("MoveBridgeImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить мост.
        /// </summary>
        internal static string MoveBridgeUserFunctionalName {
            get {
                return ResourceManager.GetString("MoveBridgeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Overpass {
            get {
                object obj = ResourceManager.GetObject("Overpass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мостовые сооружения.
        /// </summary>
        internal static string PluginToolName {
            get {
                return ResourceManager.GetString("PluginToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Podkosnaya {
            get {
                object obj = ResourceManager.GetObject("Podkosnaya", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pontoon {
            get {
                object obj = ResourceManager.GetObject("Pontoon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с геометрией.
        /// </summary>
        internal static string RotateBridgeGroupName {
            get {
                return ResourceManager.GetString("RotateBridgeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RotateBridgeImageSource {
            get {
                object obj = ResourceManager.GetObject("RotateBridgeImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поворот моста.
        /// </summary>
        internal static string RotateBridgeUserFunctionalName {
            get {
                return ResourceManager.GetString("RotateBridgeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск .
        /// </summary>
        internal static string SearchBridgeUserFunctionalName {
            get {
                return ResourceManager.GetString("SearchBridgeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string SelectBridgeDismantleGroupName {
            get {
                return ResourceManager.GetString("SelectBridgeDismantleGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectBridgeDismantleImageSource {
            get {
                object obj = ResourceManager.GetObject("SelectBridgeDismantleImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонтировать.
        /// </summary>
        internal static string SelectBridgeDismantleShortUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeDismantleShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить демонтируемые мосты.
        /// </summary>
        internal static string SelectBridgeDismantleUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeDismantleUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectBridgeImageSource {
            get {
                object obj = ResourceManager.GetObject("SelectBridgeImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string SelectBridgeRepairsGroupName {
            get {
                return ResourceManager.GetString("SelectBridgeRepairsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectBridgeRepairsImageSource {
            get {
                object obj = ResourceManager.GetObject("SelectBridgeRepairsImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ремонт.
        /// </summary>
        internal static string SelectBridgeRepairsShortUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeRepairsShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить ремонтируемые мосты.
        /// </summary>
        internal static string SelectBridgeRepairsUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeRepairsUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string SelectBridgeRequiredGroupName {
            get {
                return ResourceManager.GetString("SelectBridgeRequiredGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectBridgeRequiredImageSource {
            get {
                object obj = ResourceManager.GetObject("SelectBridgeRequiredImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется.
        /// </summary>
        internal static string SelectBridgeRequiredShortUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeRequiredShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить требуемые мосты.
        /// </summary>
        internal static string SelectBridgeRequiredUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeRequiredUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string SelectBridgeSetGroupName {
            get {
                return ResourceManager.GetString("SelectBridgeSetGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectBridgeSetImageSource {
            get {
                object obj = ResourceManager.GetObject("SelectBridgeSetImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установлен.
        /// </summary>
        internal static string SelectBridgeSetShortUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeSetShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить установленные мосты.
        /// </summary>
        internal static string SelectBridgeSetUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeSetUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string SelectBridgeTemporaryGroupName {
            get {
                return ResourceManager.GetString("SelectBridgeTemporaryGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectBridgeTemporaryImageSource {
            get {
                object obj = ResourceManager.GetObject("SelectBridgeTemporaryImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временный.
        /// </summary>
        internal static string SelectBridgeTemporaryShortUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeTemporaryShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить временные мосты.
        /// </summary>
        internal static string SelectBridgeTemporaryUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeTemporaryUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать мост.
        /// </summary>
        internal static string SelectBridgeUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectBridgeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с геометрией.
        /// </summary>
        internal static string SplitGeometryBridgesGroupName {
            get {
                return ResourceManager.GetString("SplitGeometryBridgesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplitGeometryBridgesImageSource {
            get {
                object obj = ResourceManager.GetObject("SplitGeometryBridgesImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделить геометрию.
        /// </summary>
        internal static string SplitGeometryBridgesUserFunctionalName {
            get {
                return ResourceManager.GetString("SplitGeometryBridgesUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_AngleButtressRetainingWallAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_AngleButtressRetainingWallAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_ArchedSpacerBridgeAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_ArchedSpacerBridgeAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_Columnar {
            get {
                object obj = ResourceManager.GetObject("ST_Columnar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_ColumnarCrossbarAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_ColumnarCrossbarAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_ColumnarCrossbarless {
            get {
                object obj = ResourceManager.GetObject("ST_ColumnarCrossbarless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_ColumnarWithVShapedBranch {
            get {
                object obj = ResourceManager.GetObject("ST_ColumnarWithVShapedBranch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_DoubleRowPile {
            get {
                object obj = ResourceManager.GetObject("ST_DoubleRowPile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_DoubleRowPileAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_DoubleRowPileAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_DoubleRowRack {
            get {
                object obj = ResourceManager.GetObject("ST_DoubleRowRack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_DoubleRowRackAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_DoubleRowRackAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_Frame {
            get {
                object obj = ResourceManager.GetObject("ST_Frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_Massive {
            get {
                object obj = ResourceManager.GetObject("ST_Massive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_MassiveAbutmentBackWalls {
            get {
                object obj = ResourceManager.GetObject("ST_MassiveAbutmentBackWalls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_MassiveColumnar {
            get {
                object obj = ResourceManager.GetObject("ST_MassiveColumnar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_MassiveCrumblingAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_MassiveCrumblingAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_MassiveWithCrossbar {
            get {
                object obj = ResourceManager.GetObject("ST_MassiveWithCrossbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_RackWithSwingingStruts {
            get {
                object obj = ResourceManager.GetObject("ST_RackWithSwingingStruts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_RageAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_RageAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_Ragged {
            get {
                object obj = ResourceManager.GetObject("ST_Ragged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_SingleColumnWithCrossbar {
            get {
                object obj = ResourceManager.GetObject("ST_SingleColumnWithCrossbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_SingleRowPile {
            get {
                object obj = ResourceManager.GetObject("ST_SingleRowPile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_SingleRowPileAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_SingleRowPileAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_SingleRowRack {
            get {
                object obj = ResourceManager.GetObject("ST_SingleRowRack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_SingleRowRackAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_SingleRowRackAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_SingleRowRackWithBuiltInCrossbar {
            get {
                object obj = ResourceManager.GetObject("ST_SingleRowRackWithBuiltInCrossbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_StubAbutment {
            get {
                object obj = ResourceManager.GetObject("ST_StubAbutment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_SuspensionBridgeAnchor {
            get {
                object obj = ResourceManager.GetObject("ST_SuspensionBridgeAnchor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_SuspensionBridgePylon {
            get {
                object obj = ResourceManager.GetObject("ST_SuspensionBridgePylon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ST_WallSupports {
            get {
                object obj = ResourceManager.GetObject("ST_WallSupports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SwingAxle {
            get {
                object obj = ResourceManager.GetObject("SwingAxle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tunnel {
            get {
                object obj = ResourceManager.GetObject("Tunnel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VerticalLiftSwing {
            get {
                object obj = ResourceManager.GetObject("VerticalLiftSwing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Viaduct {
            get {
                object obj = ResourceManager.GetObject("Viaduct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
