//Generated by MigrationGenerator, 27.01.2021 11:52:07
using System.Data;
using Migrator.Framework;

namespace ITS.DbMigration.Bridges
{
	/// <summary>
	/// Миграция для корректного удаления всех структур БД при откате
	/// </summary>
	[Migration(202101271152)]
	public class Migration202101271152 : Migration
	{
		public override void Up()
		{
			
		}

		public override void Down()
		{
			
		}
	}
}
